### ISSUE TITLE
Hydration issues on /minting

### ISSUE THREAD

**Issue by MSBivens** [NudeClub/NudeClubMVP#1]
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

**Comment by turingblocks** [comment]
I believe this was caused by <h1> tags within <h1> tags caused different output. error no longer presents.

**Comment by turingblocks** [comment]
closing issue as resolved
